spring.application.name=ReviewWeb_Backend

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://:@cluster0.mongodb.net/review_system?retryWrites=true&w=majority

# JWT Secret Key
jwt.secret=your-secret-key

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=profile, email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.web.cors.allowed-origin-patterns=http://localhost:3000